workers: 6
weight_decay: 0.0002
momentum: 0.9
display: 20
max_iter: 12000
batch_size: 16
test_interval: 10
topk: 3
base_lr: 0.0000004
start_iters: 0
best_model: 12345678.9
#-------------lr_policy--------------------#
lr_policy: 'multistep'
policy_parameter:
  stepvalue: [3000, 9000]
  gamma: 0.1
